### ISSUE TITLE
Serialization Object must mark MessagePackObjectAttribute. type: global::System.Ulid

### ISSUE THREAD

**Issue by NoxMortem** [Cysharp/Ulid#12]
**What happened**
- Add Ulid to project
- Add UlidMessagePackResolver and UlidMessagePackFormatter from Cysharp.Serialization.MessagePack
- Use Ulid in a `[MessagePackObject]`
- `dotnet mpc -i . -o "Visionary\Assets\Scripts\Frameworks\MessagePack"`
=> Exception

**Exception**
```stacktrace
dotnet mpc -i . -o "Visionary\Assets\Scripts\Frameworks\MessagePack"
Project Compilation Start:.
Project Compilation Complete:00:00:28.3916847
Method Collect Start
Fail in console app running on MessagepackCompiler.RunAsync
MessagePackCompiler.CodeAnalysis.MessagePackGeneratorResolveFailedException: Serialization Object must mark MessagePackObjectAttribute. type: global::System.Ulid
   at MessagePackCompiler.CodeAnalysis.TypeCollector.GetObjectInfo(INamedTypeSymbol type) in D:\a\1\s\src\MessagePack.GeneratorCore\CodeAnalysis\TypeCollector.cs:line 610
   at MessagePackCompiler.CodeAnalysis.TypeCollector.CollectObject(INamedTypeSymbol type) in D:\a\1\s\src\MessagePack.GeneratorCore\CodeAnalysis\TypeCollector.cs:line 604
   at MessagePackCompiler.CodeAnalysis.TypeCollector.CollectCore(ITypeSymbol typeSymbol) in D:\a\1\s\src\MessagePack.GeneratorCore\CodeAnalysis\TypeCollector.cs:line 392
   at MessagePackCompiler.CodeAnalysis.TypeCollector.CollectGeneric(INamedTypeSymbol type) in D:\a\1\s\src\MessagePack.GeneratorCore\CodeAnalysis\TypeCollector.cs:line 522
   at MessagePackCompiler.CodeAnalysis.TypeCollector.CollectCore(ITypeSymbol typeSymbol) in D:\a\1\s\src\MessagePack.GeneratorCore\CodeAnalysis\TypeCollector.cs:line 371
   at MessagePackCompiler.CodeAnalysis.TypeCollector.GetObjectInfo(INamedTypeSymbol type) in D:\a\1\s\src\MessagePack.GeneratorCore\CodeAnalysis\TypeCollector.cs:line 784
   at MessagePackCompiler.CodeAnalysis.TypeCollector.CollectObject(INamedTypeSymbol type) in D:\a\1\s\src\MessagePack.GeneratorCore\CodeAnalysis\TypeCollector.cs:line 604
   at MessagePackCompiler.CodeAnalysis.TypeCollector.CollectCore(ITypeSymbol typeSymbol) in D:\a\1\s\src\MessagePack.GeneratorCore\CodeAnalysis\TypeCollector.cs:line 392
   at MessagePackCompiler.CodeAnalysis.TypeCollector.Collect() in D:\a\1\s\src\MessagePack.GeneratorCore\CodeAnalysis\TypeCollector.cs:line 323
   at MessagePackCompiler.CodeGenerator.GenerateFileAsync(String input, String output, String conditionalSymbol, String resolverName, String namespace, Boolean useMapMode, String multipleIfDirectiveOutputSymbols) in D:\a\1\s\src\MessagePack.GeneratorCore\CodeGenerator.cs:line 58
   at MessagePack.Generator.MessagepackCompiler.RunAsync(String input, String output, String conditionalSymbol, String resolverName, String namespace, Boolean useMapMode, String multipleIfDirectiveOutputSymbols) in D:\a\1\s\src\MessagePack.Generator\MessagepackCompiler.cs:line 30
   at ConsoleAppFramework.ConsoleAppEngine.RunCore(ConsoleAppContext ctx, Type type, MethodInfo methodInfo, String[] args, Int32 argsOffset)
```

**Expected**
Regenerate the generated formatters and resolvers for classes flagged as `[MessagePackObject]` in all *.csproj files in `.\**`

**Additional information**
The same error occurs when running on a single csproj `dotnet mpc -i "Application.csproj" -o "Visionary\Assets\Scripts\Frameworks\MessagePack"` with the following `[MessagePackObject]` classes
```c#
using System;
using MessagePack;

namespace Application.Project.Files.Mpk
{
	[MessagePackObject]
	public class UlidFileMpk
	{		
		[IgnoreMember]
		public string OpenedDirectory;

		[Key(0)]
		public Ulid Ulid = Ulid.NewUlid();
	}
}
```
```c#
using System;
using System.Collections.Generic;
using MessagePack;

namespace Application.Project.Files.Mpk
{
	[MessagePackObject]
	public class ProjectCacheRegistryMpk
	{
		[Key(0)]
		public Dictionary<Ulid, string> UlidToRelativePath = new Dictionary<Ulid, string>();

		[IgnoreMember]
		public string OpenedDirectory;

		public bool TryGetRelativePath(Ulid ulid, out string relativePath) => UlidToRelativePath.TryGetValue(ulid, out relativePath);

		public void Add(Ulid ulid, string relativePath) => UlidToRelativePath.Add(ulid, relativePath);
	}
}
```

**Platform & Version**
- Unity 2020.1.2f1
- Ulid 1.0.0
- `dotnet --version` 3.1.401
- mpc installed locally `dotnet tool install MessagePack.Generator`

**Comment by NoxMortem** [comment]
I have added `[MessagePackObject] to Ulid, and added a Reference to MessagePack.csproj (via .asmdef as per Unity) and that solve it _for me_, but I still wonder what the actual fix would be. I assume mpc would require a feature to skip certain classes for generation, if they already have a Resolver and Formatter (wherever it comes from).

Furthermore, this might be related to https://github.com/neuecc/MessagePack-CSharp/issues/1017

**Comment by neuecc** [comment]
Thanks, this should fix in mpc, I've sent PR https://github.com/neuecc/MessagePack-CSharp/pull/1019
